- name: judge if docker is exist
  shell: command -v dockerd >/dev/null 2>&1
  register: docker_install
  failed_when: "'command not found' in docker_install.stderr"

- name: clean docker exits
  when: docker_install.rc == 0
  include_tasks: clean_docker.yml

