- name: create some dirs
  file:
    path: "{{item}}"
    state: directory
  with_items:
  - "{{install_home}}/redis"
  - "{{redis_work_dir}}"

- name: copy redis.tar and redis_init.sh
  copy:
    src: "{{install_home}}/pkg/redis/{{item}}"
    dest: "{{install_home}}/redis/{{item}}"
    force: no
    mode: 0755
  with_items:
  - redis.tar
  - redis_init.sh

- name: translate templates to conf
  template:
    src: "{{install_home}}/yml_books/roles/redis/templates/{{redis_node_name}}.conf.j2"
    dest: "{{redis_work_dir}}/redis.conf"

- name: run redis
  shell: "sh {{install_home}}/redis/redis_init.sh" 
