- name: create some dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{install_home}}/redis"

- name: copy redis.tar.xz
  copy:
    src: "{{install_home}}/pkg/redis/{{item}}"
    dest: "{{install_home}}/redis/{{item}}"
    force: no
    mode: 0755
  with_items:
  - redis.tar.xz

- name: install docker
  shell: "rpm -Uvh {{install_home}}/docker/*.rpm"
  ignore_errors: true

- name: copy docker service
  copy:
    src: "{{install_home}}/yml_books/roles/install_docker/templates/{{item}}"
    dest: "/etc/systemd/system/{{item}}"
    force: no
    mode: 0644
    backup: yes
  with_items:
  - docker.service

- name: copy daemon.json to accelerate
  copy:
    src: "{{install_home}}/yml_books/roles/install_docker/templates/{{item}}"
    dest: "/etc/docker/{{item}}"
    force: no
    mode: 0644
  with_items:
  - daemon.json

- name: run docker
  shell: "sh {{install_home}}/docker/run_docker.sh" 
