- name: "generate ssh key file"
  shell: 'ssh-keygen -b 2048 -t rsa -q -N "" -f /root/.ssh/id_rsa'
  delegate_to: localhost
  run_once: true

- name: "prepare sshpass"
  shell: 'command -v sshpass || rpm -Uvh {{pkg_home}}/ansible/sshpass-1.06-2.el7.x86_64.rpm'
  delegate_to: localhost
  run_once: true

